from .doctorRegistView import DoctorRegistView
from .nurseRegistView import NurseRegistView
from .recordRegistView import RecordRegistView
from .patientrecordRegistView import Patient_RecordRegistView
from .consultationRegistView import ConsultationRegistView
from .developmentSerializer import DevelopmentRegistView
from .patientRegistView import PatientRegistView
from .procedureRegistView import ProcedureRegistView
from .hospitalListView import HospitalListView
from .tokenCRUDView import TokenCRUDView
from .procedureListView import ProcedureListView
from .epsListView import EpsListView
from .recordListView import RecordListView
from .patientRUDView import PatientRUDView
from .patientListView import PatientListView
from .doctorRUDView import DoctorRUDView
from .nurseRUDView import NurseRUDView
from .patientRecordListView import PatientRecordListView
from .developmentListView import DevelopmentListView
from .consultationListView import ConsultationListView
from .doctorListView import DoctorListView
from .consultationRUDView import ConsultationRUDView
from .nurseListView import NurseListView
from .developmentRUDView import DevelopmentRUDView
from .recordRUDView import RecordRUDView
from .patientRecordRUDView import PatientRecordRUDView
from .procedureRUDView import ProcedureRUDView
from .workLabor import WorkView