# Generated by Django 3.2.8 on 2021-10-31 05:13

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Eps',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Nombre de la Eps')),
            ],
            options={
                'verbose_name': 'Eps',
                'verbose_name_plural': 'Eps',
            },
        ),
        migrations.CreateModel(
            name='Hospital',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Nombre del Hospital')),
                ('address', models.CharField(max_length=100, verbose_name='Dirección')),
                ('city', models.CharField(max_length=100, verbose_name='Ciudad')),
            ],
            options={
                'verbose_name': 'Hospital',
                'verbose_name_plural': 'Hospitales',
            },
        ),
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('identification', models.IntegerField(verbose_name='Cedula')),
                ('date_of_birth', models.DateTimeField(verbose_name='Fecha de Nacimiento')),
                ('phone', models.BigIntegerField(blank=True, null=True, verbose_name='Teléfono')),
                ('marital_status', models.CharField(blank=True, max_length=200, null=True, verbose_name='Estado Civil')),
                ('blood_type', models.CharField(max_length=200, verbose_name='Grupo Sanguineo')),
                ('eps', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='petient', to='medsource.eps')),
            ],
            options={
                'verbose_name': 'Paciente',
                'verbose_name_plural': 'Pacientes',
            },
        ),
        migrations.CreateModel(
            name='Nurse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('identification', models.IntegerField(verbose_name='Cedula')),
                ('education', models.CharField(max_length=200, verbose_name='Formación')),
                ('area', models.CharField(max_length=200, verbose_name='Area')),
                ('hospital', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='nurse', to='medsource.hospital')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='nurse', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Enfermero',
                'verbose_name_plural': 'Enfermeros',
            },
        ),
        migrations.CreateModel(
            name='Doctor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('identification', models.IntegerField(verbose_name='Cedula')),
                ('education', models.CharField(max_length=200, verbose_name='Formación')),
                ('specialization', models.CharField(blank=True, max_length=200, null=True, verbose_name='Especialización')),
                ('hospital', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='doctor', to='medsource.hospital')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='doctor', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Doctor',
                'verbose_name_plural': 'Doctores',
            },
        ),
    ]
