# Generated by Django 3.2.8 on 2021-10-31 16:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medsource', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doctor',
            name='identification',
            field=models.IntegerField(unique=True, verbose_name='Cedula'),
        ),
        migrations.AlterField(
            model_name='nurse',
            name='identification',
            field=models.IntegerField(unique=True, verbose_name='Cedula'),
        ),
        migrations.AlterField(
            model_name='patient',
            name='identification',
            field=models.IntegerField(unique=True, verbose_name='Cedula'),
        ),
    ]
