# Generated by Django 3.2.9 on 2021-11-04 18:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('medsource', '0002_auto_20211031_1647'),
    ]

    operations = [
        migrations.CreateModel(
            name='Procedure',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Nombre del procedimiento')),
                ('uvr', models.IntegerField(verbose_name='UVR')),
            ],
            options={
                'verbose_name': 'Procedimiento',
                'verbose_name_plural': 'Procedimientos',
            },
        ),
        migrations.CreateModel(
            name='Record',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Nombre del antecedente')),
                ('kind', models.CharField(max_length=200, verbose_name='Tipo')),
                ('sort', models.CharField(max_length=200, verbose_name='Clase')),
            ],
            options={
                'verbose_name': 'Antecedente',
                'verbose_name_plural': 'Antecedentes',
            },
        ),
        migrations.AlterField(
            model_name='patient',
            name='date_of_birth',
            field=models.DateField(verbose_name='Fecha de Nacimiento'),
        ),
        migrations.AlterField(
            model_name='patient',
            name='eps',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='patient', to='medsource.eps'),
        ),
        migrations.CreateModel(
            name='Patient_Record',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='presencia', to='medsource.patient')),
                ('record', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='presencia', to='medsource.record')),
            ],
            options={
                'verbose_name': 'Presencia de antecedente',
                'verbose_name_plural': 'Presencia de antecedentes',
            },
        ),
        migrations.CreateModel(
            name='Development',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='Fecha')),
                ('room', models.CharField(max_length=200, verbose_name='Sala')),
                ('comment', models.CharField(blank=True, max_length=200, null=True, verbose_name='Comentario')),
                ('doctor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='desarrollo', to='medsource.doctor')),
                ('hospital', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='desarrollo', to='medsource.hospital')),
                ('nurse', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='desarrollo', to='medsource.nurse')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='desarrollo', to='medsource.patient')),
                ('procedure', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='desarrollo', to='medsource.procedure')),
            ],
            options={
                'verbose_name': 'Desarrollo',
                'verbose_name_plural': 'Desarrollos',
            },
        ),
        migrations.CreateModel(
            name='Consultation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pulse', models.IntegerField(blank=True, null=True, verbose_name='Pulso')),
                ('height', models.IntegerField(blank=True, null=True, verbose_name='Altura')),
                ('weight', models.IntegerField(blank=True, null=True, verbose_name='Peso')),
                ('pa', models.IntegerField(blank=True, null=True, verbose_name='Pa')),
                ('pr', models.IntegerField(blank=True, null=True, verbose_name='Pr')),
                ('t', models.IntegerField(blank=True, null=True, verbose_name='T')),
                ('medication', models.CharField(blank=True, max_length=200, null=True, verbose_name='Medicamento')),
                ('symptom', models.CharField(blank=True, max_length=200, null=True, verbose_name='Sintoma')),
                ('diagnosis', models.CharField(blank=True, max_length=200, null=True, verbose_name='Diagnostico')),
                ('doctor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='consulta', to='medsource.doctor')),
                ('hospital', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='consulta', to='medsource.hospital')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='consulta', to='medsource.patient')),
            ],
            options={
                'verbose_name': 'Consulta',
                'verbose_name_plural': 'Consultas',
            },
        ),
    ]
