# Generated by Django 3.2.8 on 2021-11-28 02:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medsource', '0004_token'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='token',
            name='id',
        ),
        migrations.AlterField(
            model_name='token',
            name='token',
            field=models.UUIDField(auto_created=True, primary_key=True, serialize=False, unique=True, verbose_name='Token'),
        ),
    ]
